"/":
  controller: App\Controller\PagesController
  action: default

"/liste_des_utilisateurs":
  controller: App\Controller\UsersController
  action: default

"/ajouter_un_utilisateur":
  controller: App\Controller\UsersController
  action: add


"/enregistrer_un_utilisateur":
  controller: App\Controller\UsersController
  action: save

"/connexion":
  controller: App\Controller\UsersController
  action: login

"/mot_de_passe_oublie":
  controller: App\Controller\UsersController
  action: forgetPassword